---
- name: Setup Minecraft Server
  hosts: minecraft
  become: yes

  tasks:
    - name: Install Java 21
      dnf:
        name: java-21-amazon-corretto
        state: present

    - name: Create Minecraft directory
      file:
        path: /home/ec2-user/minecraft
        state: directory
        owner: ec2-user

    - name: Download Minecraft server jar
      get_url:
        url: https://launcher.mojang.com/v1/objects/e6ec2f64e6080b9b5d9b471b291c33cc7f509733/server.jar
        dest: /home/ec2-user/minecraft/server.jar
        owner: ec2-user

    - name: Accept EULA
      copy:
        dest: /home/ec2-user/minecraft/eula.txt
        content: "eula=true\n"
        owner: ec2-user

    - name: Create start.sh script
      copy:
        dest: /home/ec2-user/minecraft/start.sh
        content: |
          #!/bin/bash
          java -Xmx1024M -Xms1024M -jar server.jar nogui
        mode: '0755'
        owner: ec2-user

    - name: Create systemd service
      copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft Server
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/home/ec2-user/minecraft
          ExecStart=/usr/bin/java -Xmx1024M -Xms1024M -jar server.jar nogui
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
      mode: '0644'

    - name: Enable and start the Minecraft service
      systemd:
        name: minecraft
        enabled: yes
        state: started
